spring:
  profiles:
    active: dev
  application:
    name: servicio-eureka
---
# Entorno de desarrollo
spring:
  profiles: dev
eureka:
  client:
    fetchRegistry: 'false'
    registerWithEureka: 'false'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: '8761'
---
# Entorno de prod
spring:
  profiles: prod
eureka:
  client:
    fetchRegistry: 'false'
    registerWithEureka: 'false'
    serviceUrl:
      defaultZone: http://servicio-eureka-server:8761/eureka
server:
  port: '8761'