spring:
  profiles:
    active: dev
  application:
    name: gateway
    
---
# Entorno de desarrollo
spring:
  profiles: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: MSVC-CLIENT
          uri: lb://MSVC-CLIENT
          predicates:
            - Path=/clients/**
        - id: msvc-product
          uri: lb://msvc-product
          predicates: 
            - Path=/product/**
        - id: msvc-account
          uri: lb://msvc-account
          predicates: 
            - Path=/account/**
        - id: msvc-operation
          uri: lb://msvc-operation
          predicates: 
            - Path=/operation/**    

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

info:
  app:
    version: 1.0.0
    name: Gateway
    description: Centralizes and routes all requests from the outside to each microservice

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
  info:
    env:
      enabled: true

server:
  port: 8081
---
# Entorno de prod
spring:
  profiles: prod
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: MSVC-CLIENT
          uri: lb://MSVC-CLIENT
          predicates:
            - Path=/clients/**
        - id: msvc-product
          uri: lb://msvc-product
          predicates: 
            - Path=/product/**
        - id: msvc-account
          uri: lb://msvc-account
          predicates: 
            - Path=/account/**
        - id: msvc-operation
          uri: lb://msvc-operation
          predicates: 
            - Path=/operation/**   
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
       defaultZone: http://localhost:8761/eureka
      # defaultZone: http://servicio-eureka-server:8761/eureka
  instance:
    preferIpAddress: true

info:
  app:
    version: 1.0.0
    name: Gateway
    description: Centralizes and routes all requests from the outside to each microservice

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
  info:
    env:
      enabled: true

server:
  port: 8081
