spring:
  profiles.active: dev
  
---
server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
 profiles: dev 
 data:
   mongodb:
       database: bankoperation
       uri: mongodb+srv://root:XR1dZNfCu7G7vbYL@cluster0.rc9rpyb.mongodb.net/?retryWrites=true&w=majority
       #uri: mongodb://localhost:27017/operation



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: 'info'
  info:
    env:
      enabled: true
info:
  app:
    version: 1.0.0
    name: Microservices operation
    description: Microservices related to the maintenance of operation     


---
server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
 profiles: prod 
 data:
   mongodb:
       database: bankoperation
       uri: mongodb+srv://root:XR1dZNfCu7G7vbYL@cluster0.rc9rpyb.mongodb.net/?retryWrites=true&w=majority


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: 'info'
  info:
    env:
      enabled: true
info:
  app:
    version: 1.0.0
    name: Microservices operation
    description: Microservices related to the maintenance of operation   
    
